modLoader="javafml"
loaderVersion="[14,)"
license="All Rights Reserved"

[[mods]]
modId="divineblade"
version="1.0.0"
displayName="Divine Blade"
authors="YourName"
description='''
A divine weapon with absolute power.
'''

[[dependencies.divineblade]]
modId="neoforge"
mandatory=true
versionRange="[20.4.205,)"
ordering="NONE"
side="BOTH"

[[dependencies.divineblade]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
