modLoader="javafml"
loaderVersion="[20,)"
license="MIT"

[[mods]]
modId="divineblade"
version="${file.jarVersion}"
displayName="Divine Blade"
authors="YourName"
description='''
A divine weapon with absolute power.
'''

[[dependencies.divineblade]]
modId="neoforge"
mandatory=true
versionRange="[20.4.179,)"
ordering="NONE"
side="BOTH"

[[dependencies.divineblade]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
